document.write("<nav class=\"wiki-navigation\">");
document.write("  <ul class=\"wiki-navigation-tabs\">");
document.write("    <li class=\"wiki-navigation-dropdown\">");
document.write("      <div class=\"wiki-navigation-first-dropdown\">");
document.write("        <a style=\"pointer-events: none; cursor: default;\">");
document.write("          <svg class=\"tiny-icons\">");
document.write("            <path id=\"book-tiny\" d=\"M3.5 3C2.673 3 2 3.673 2 4.5v2.338c.91-.434 2.09-.434 3 0V4.5c0-.397-.159-.785-.437-1.063A1.513 1.513 0 0 0 3.5 3m5 3.5c.537 0 1.045.121 1.5.338V4.5c0-.397-.159-.785-.437-1.063A1.502 1.502 0 0 0 7 4.5v2.338A3.473 3.473 0 0 1 8.5 6.5M11 11a1 1 0 0 1-1-1c0-.827-.673-1.5-1.5-1.5S7 9.173 7 10a1 1 0 1 1-2 0c0-.827-.673-1.5-1.5-1.5S2 9.173 2 10a1 1 0 1 1-2 0V4.5a3.504 3.504 0 0 1 5.977-2.477l.026.027A3.489 3.489 0 0 1 8.5 1c.937 0 1.817.363 2.477 1.023A3.524 3.524 0 0 1 12 4.5V10a1 1 0 0 1-1 1\" />");
document.write("          </svg>");
document.write("          <span class=\"navigation-label\" style=\"margin-left: 20px;\">გამოკვლევა</span>");
document.write("        </a>");
document.write("        <svg class=\"dropdown-icons dropdown-toggle\">");
document.write("          <path id=\"dropdown-tiny-a\" d=\"M6.0001895,8.80004571 C5.79538755,8.80004571 5.5905856,8.72164496 5.43458411,8.56564348 L2.23455364,5.365613 C2.00575146,5.13681083 1.93695081,4.79280755 2.06095199,4.4936047 C2.18415316,4.19440185 2.47695595,4 2.80015903,4 L9.20021997,4 C9.52342305,4 9.81542583,4.19440185 9.93942701,4.4936047 C10.0634282,4.79280755 9.99462754,5.13681083 9.76582536,5.365613 L6.56579489,8.56564348 C6.4097934,8.72164496 6.20499145,8.80004571 6.0001895,8.80004571 Z\" />");
document.write("        </svg>");
document.write("      </div>");
document.write("      <div class=\"dropdown-menu\">");
document.write("        <ul class=\"wiki-navigation-lists\">");
document.write("          <li>");
document.write("            <a href=\"/\">");
document.write("              <svg class=\"dropdown-icons\" style=\"margin-right: 6px;\">");
document.write("                <path id=\"home-tiny\" d=\"M9 10h1V6.414l-4-4-4 4V10h1V9c0-1.654 1.346-3 3-3s3 1.346 3 3v1zm2 2H8a1 1 0 0 1-1-1V9c0-.55-.449-1-1-1-.551 0-1 .45-1 1v2a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V6c0-.265.105-.52.293-.707l5-5a.999.999 0 0 1 1.414 0l5 5A.997.997 0 0 1 12 6v5a1 1 0 0 1-1 1z\" fill=\"#fff\" />");
document.write("              </svg>");
document.write("              <span>მთავარი გვერდი</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Category-All_Pages.html\">");
document.write("              <span>ყველა გვერდი</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Special-Random.html\">");
document.write("              <span>შემთხვევითი გვერდი</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Special-Special_Pages.html\">");
document.write("              <span>სპეციალური გვერდები</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Category-Categories.html\">");
document.write("              <span>კატეგორიები</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Special-Images.html\">");
document.write("              <span>სურათები</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"Special-Videos.html\">");
document.write("              <span>ვიდეოები</span>");
document.write("            </a>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </li>");
document.write("    <li class=\"wiki-navigation-dropdown\">");
document.write("      <div class=\"wiki-navigation-first-dropdown\">");
document.write("        <a href=\"", NavItem1URL, "\">");
document.write("          <span>", NavItem1, "</span>");
document.write("        </a>");
document.write("        <svg class=\"dropdown-icons dropdown-toggle\">");
document.write("          <use href=\"#dropdown-tiny-a\"></use>");
document.write("        </svg>");
document.write("      </div>");
document.write("      <div class=\"dropdown-menu\">");
document.write("        <ul class=\"wiki-navigation-lists\">");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem11URL, "\">");
document.write("              <span>", NavItem11, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <path id=\"sublist-arrow\" d=\"M11.707 3.293a.999.999 0 0 0-1.414 0L6 7.586 1.707 3.293A.999.999 0 1 0 .293 4.707l5 5a.997.997 0 0 0 1.414 0l5-5a.999.999 0 0 0 0-1.414\" fill=\"#737373\" />");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem111URL, "\">");
document.write("                    <span>", NavItem111, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem112URL, "\">");
document.write("                    <span>", NavItem112, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem113URL, "\">");
document.write("                    <span>", NavItem113, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem114URL, "\">");
document.write("                    <span>", NavItem114, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem115URL, "\">");
document.write("                    <span>", NavItem115, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem116URL, "\">");
document.write("                    <span>", NavItem116, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem117URL, "\">");
document.write("                    <span>", NavItem117, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem118URL, "\">");
document.write("                    <span>", NavItem118, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem119URL, "\">");
document.write("                    <span>", NavItem119, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem1110URL, "\">");
document.write("                    <span>", NavItem1110, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem12URL, "\">");
document.write("              <span>", NavItem12, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <use href=\"#sublist-arrow\"></use>");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem121URL, "\">");
document.write("                    <span>", NavItem121, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem122URL, "\">");
document.write("                    <span>", NavItem122, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem123URL, "\">");
document.write("                    <span>", NavItem123, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem124URL, "\">");
document.write("                    <span>", NavItem124, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem125URL, "\">");
document.write("                    <span>", NavItem125, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem126URL, "\">");
document.write("                    <span>", NavItem126, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem127URL, "\">");
document.write("                    <span>", NavItem127, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem128URL, "\">");
document.write("                    <span>", NavItem128, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem129URL, "\">");
document.write("                    <span>", NavItem129, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem1210URL, "\">");
document.write("                    <span>", NavItem1210, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem13URL, "\">");
document.write("              <span>", NavItem13, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <use href=\"#sublist-arrow\"></use>");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem131URL, "\">");
document.write("                    <span>", NavItem131, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem122URL, "\">");
document.write("                    <span>", NavItem132, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem133URL, "\">");
document.write("                    <span>", NavItem133, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem134URL, "\">");
document.write("                    <span>", NavItem134, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem135URL, "\">");
document.write("                    <span>", NavItem135, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem136URL, "\">");
document.write("                    <span>", NavItem136, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem137URL, "\">");
document.write("                    <span>", NavItem137, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem138URL, "\">");
document.write("                    <span>", NavItem138, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem139URL, "\">");
document.write("                    <span>", NavItem139, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem1310URL, "\">");
document.write("                    <span>", NavItem1310, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem14URL, "\">");
document.write("              <span>", NavItem14, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <use href=\"#sublist-arrow\"></use>");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem141URL, "\">");
document.write("                    <span>", NavItem141, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem142URL, "\">");
document.write("                    <span>", NavItem142, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem143URL, "\">");
document.write("                    <span>", NavItem143, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem144URL, "\">");
document.write("                    <span>", NavItem144, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem145URL, "\">");
document.write("                    <span>", NavItem145, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem146URL, "\">");
document.write("                    <span>", NavItem146, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem147URL, "\">");
document.write("                    <span>", NavItem147, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem148URL, "\">");
document.write("                    <span>", NavItem148, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem149URL, "\">");
document.write("                    <span>", NavItem149, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem1410URL, "\">");
document.write("                    <span>", NavItem1410, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem15URL, "\">");
document.write("              <span>", NavItem15, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <use href=\"#sublist-arrow\"></use>");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem151URL, "\">");
document.write("                    <span>", NavItem151, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem152URL, "\">");
document.write("                    <span>", NavItem152, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem153URL, "\">");
document.write("                    <span>", NavItem153, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem154URL, "\">");
document.write("                    <span>", NavItem154, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem155URL, "\">");
document.write("                    <span>", NavItem155, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem156URL, "\">");
document.write("                    <span>", NavItem156, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem157URL, "\">");
document.write("                    <span>", NavItem157, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem158URL, "\">");
document.write("                    <span>", NavItem158, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem159URL, "\">");
document.write("                    <span>", NavItem159, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem1510URL, "\">");
document.write("                    <span>", NavItem1510, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("          <li class=\"navigation-sublists\">");
document.write("            <a href=\"", NavItem16URL, "\">");
document.write("              <span>", NavItem16, "</span>");
document.write("              <svg class=\"sublist-icons\">");
document.write("                <use href=\"#sublist-arrow\"></use>");
document.write("              </svg>");
document.write("            </a>");
document.write("            <div class=\"wiki-sublist-contents\" style=\"bottom: -10px; top: unset;\">");
document.write("              <ul class=\"wiki-navigation-lists\">");
document.write("                <li>");
document.write("                  <a href=\"", NavItem161URL, "\">");
document.write("                    <span>", NavItem161, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem162URL, "\">");
document.write("                    <span>", NavItem162, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("                <li>");
document.write("                  <a href=\"", NavItem163URL, "\">");
document.write("                    <span>", NavItem163, "</span>");
document.write("                  </a>");
document.write("                </li>");
document.write("              </ul>");
document.write("            </div>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </li>");
document.write("    <li class=\"wiki-navigation-dropdown\">");
document.write("      <div class=\"wiki-navigation-first-dropdown\">");
document.write("        <a href=\"", NavItem2URL, "\">");
document.write("          <span>", NavItem2, "</span>");
document.write("        </a>");
document.write("        <svg class=\"dropdown-icons dropdown-toggle\">");
document.write("          <use href=\"#dropdown-tiny-a\"></use>");
document.write("        </svg>");
document.write("      </div>");
document.write("      <div class=\"dropdown-menu\">");
document.write("        <ul class=\"wiki-navigation-lists\">");
document.write("          <li>");
document.write("            <a href=\"", NavItem21URL, "\">");
document.write("              <span>", NavItem21, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem22URL, "\">");
document.write("              <span>", NavItem22, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem23URL, "\">");
document.write("              <span>", NavItem23, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem24URL, "\">");
document.write("              <span>", NavItem24, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem25URL, "\">");
document.write("              <span>", NavItem25, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem26URL, "\">");
document.write("              <span>", NavItem26, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem27URL, "\">");
document.write("              <span>", NavItem27, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem28URL, "\">");
document.write("              <span>", NavItem28, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem29URL, "\">");
document.write("              <span>", NavItem29, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem210URL, "\">");
document.write("              <span>", NavItem210, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </li>");
document.write("    <li class=\"wiki-navigation-dropdown\">");
document.write("      <div class=\"wiki-navigation-first-dropdown\">");
document.write("        <a href=\"", NavItem3URL, "\">");
document.write("          <span>", NavItem3, "</span>");
document.write("        </a>");
document.write("        <svg class=\"dropdown-icons dropdown-toggle\">");
document.write("          <use href=\"#dropdown-tiny-a\"></use>");
document.write("        </svg>");
document.write("      </div>");
document.write("      <div class=\"dropdown-menu\">");
document.write("        <ul class=\"wiki-navigation-lists\">");
document.write("          <li>");
document.write("            <a href=\"", NavItem31URL, "\">");
document.write("              <span>", NavItem31, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem32URL, "\">");
document.write("              <span>", NavItem32, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem33URL, "\">");
document.write("              <span>", NavItem33, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem34URL, "\">");
document.write("              <span>", NavItem34, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem35URL, "\">");
document.write("              <span>", NavItem35, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem36URL, "\">");
document.write("              <span>", NavItem36, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem37URL, "\">");
document.write("              <span>", NavItem37, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem38URL, "\">");
document.write("              <span>", NavItem38, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem39URL, "\">");
document.write("              <span>", NavItem39, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem310URL, "\">");
document.write("              <span>", NavItem310, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </li>");
document.write("    <li class=\"wiki-navigation-dropdown\">");
document.write("      <div class=\"wiki-navigation-first-dropdown\">");
document.write("        <a href=\"", NavItem4URL, "\">");
document.write("          <span>", NavItem4, "</span>");
document.write("        </a>");
document.write("        <svg class=\"dropdown-icons dropdown-toggle\">");
document.write("          <use href=\"#dropdown-tiny-a\"></use>");
document.write("        </svg>");
document.write("      </div>");
document.write("      <div class=\"dropdown-menu\">");
document.write("        <ul class=\"wiki-navigation-lists\">");
document.write("          <li>");
document.write("            <a href=\"", NavItem41URL, "\">");
document.write("              <span>", NavItem41, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem42URL, "\">");
document.write("              <span>", NavItem42, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem43URL, "\">");
document.write("              <span>", NavItem43, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem44URL, "\">");
document.write("              <span>", NavItem44, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem45URL, "\">");
document.write("              <span>", NavItem45, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem46URL, "\">");
document.write("              <span>", NavItem46, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem47URL, "\">");
document.write("              <span>", NavItem47, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem48URL, "\">");
document.write("              <span>", NavItem48, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem49URL, "\">");
document.write("              <span>", NavItem49, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("          <li>");
document.write("            <a href=\"", NavItem410URL, "\">");
document.write("              <span>", NavItem410, "</span>");
document.write("            </a>");
document.write("          </li>");
document.write("        </ul>");
document.write("      </div>");
document.write("    </li>");
document.write("  </ul>");
document.write("</nav>");
