// var toc_header_1 = "";
// var toc_subheader_11 = "";
// var toc_subheader_12 = "";
// var toc_subheader_13 = "";
// var toc_subheader_14 = "";
// var toc_subheader_15 = "";
// var toc_subheader_16 = "";
// var toc_subheader_17 = "";
// var toc_subheader_18 = "";
// var toc_subheader_19 = "";
// var toc_subheader_110 = "";
// var toc_header_2 = "";
// var toc_subheader_21 = "";
// var toc_subheader_22 = "";
// var toc_subheader_23 = "";
// var toc_subheader_24 = "";
// var toc_subheader_25 = "";
// var toc_subheader_26 = "";
// var toc_subheader_27 = "";
// var toc_subheader_28 = "";
// var toc_subheader_29 = "";
// var toc_subheader_210 = "";
// var toc_header_3 = "";
// var toc_subheader_31 = "";
// var toc_subheader_32 = "";
// var toc_subheader_33 = "";
// var toc_subheader_34 = "";
// var toc_subheader_35 = "";
// var toc_subheader_36 = "";
// var toc_subheader_37 = "";
// var toc_subheader_38 = "";
// var toc_subheader_39 = "";
// var toc_subheader_310 = "";
// var toc_header_4 = "";
// var toc_subheader_41 = "";
// var toc_subheader_42 = "";
// var toc_subheader_43 = "";
// var toc_subheader_44 = "";
// var toc_subheader_45 = "";
// var toc_subheader_46 = "";
// var toc_subheader_47 = "";
// var toc_subheader_48 = "";
// var toc_subheader_49 = "";
// var toc_subheader_410 = "";
// var toc_header_5 = "";
// var toc_subheader_51 = "";
// var toc_subheader_52 = "";
// var toc_subheader_53 = "";
// var toc_subheader_54 = "";
// var toc_subheader_55 = "";
// var toc_subheader_56 = "";
// var toc_subheader_57 = "";
// var toc_subheader_58 = "";
// var toc_subheader_59 = "";
// var toc_subheader_510 = "";
// var toc_header_6 = "";
// var toc_subheader_61 = "";
// var toc_subheader_62 = "";
// var toc_subheader_63 = "";
// var toc_subheader_64 = "";
// var toc_subheader_65 = "";
// var toc_subheader_66 = "";
// var toc_subheader_67 = "";
// var toc_subheader_68 = "";
// var toc_subheader_69 = "";
// var toc_subheader_610 = "";
// var toc_header_7 = "";
// var toc_subheader_71 = "";
// var toc_subheader_72 = "";
// var toc_subheader_73 = "";
// var toc_subheader_74 = "";
// var toc_subheader_75 = "";
// var toc_subheader_76 = "";
// var toc_subheader_77 = "";
// var toc_subheader_78 = "";
// var toc_subheader_79 = "";
// var toc_subheader_710 = "";
// var toc_header_8 = "";
// var toc_subheader_81 = "";
// var toc_subheader_82 = "";
// var toc_subheader_83 = "";
// var toc_subheader_84 = "";
// var toc_subheader_85 = "";
// var toc_subheader_86 = "";
// var toc_subheader_87 = "";
// var toc_subheader_88 = "";
// var toc_subheader_89 = "";
// var toc_subheader_810 = "";
// var toc_header_9 = "";
// var toc_subheader_91 = "";
// var toc_subheader_92 = "";
// var toc_subheader_93 = "";
// var toc_subheader_94 = "";
// var toc_subheader_95 = "";
// var toc_subheader_96 = "";
// var toc_subheader_97 = "";
// var toc_subheader_98 = "";
// var toc_subheader_99 = "";
// var toc_subheader_910 = "";
// var toc_header_10 = "";
// var toc_subheader_101 = "";
// var toc_subheader_102 = "";
// var toc_subheader_103 = "";
// var toc_subheader_104 = "";
// var toc_subheader_105 = "";
// var toc_subheader_106 = "";
// var toc_subheader_107 = "";
// var toc_subheader_108 = "";
// var toc_subheader_109 = "";
// var toc_subheader_1010 = "";


if (typeof toc_header_1 !== 'undefined') {
document.write("<div id=\"toc\">");
document.write("");
document.write("        <input type=\"checkbox\" role=\"button\" id=\"toctogglecheckbox\" class=\"toctogglecheckbox\" style=\"display:none\">");
document.write("");
document.write("        <div class=\"toctitle\" id=\"toctitle\">");
document.write("            <h2>");
document.write("                <svg>");
document.write("                    <path id=\"bulleted-list-tiny\" d=\"M1.29 9.277c-.181.19-.29.45-.29.71 0 .26.109.52.29.71.189.18.45.29.71.29.26 0 .519-.11.71-.29.18-.19.29-.45.29-.71 0-.26-.11-.52-.29-.71-.38-.37-1.05-.37-1.42 0M10 9H6a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2M6 3h4a1 1 0 1 0 0-2H6a1 1 0 1 0 0 2m4 2H6a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2M1.29 1.277c.37-.37 1.04-.37 1.42 0 .18.19.29.45.29.71 0 .26-.11.52-.29.71-.191.18-.45.29-.71.29-.26 0-.521-.11-.71-.29-.181-.19-.29-.45-.29-.71 0-.26.109-.52.29-.71zM2.55 5.17c.06.03.11.08.16.12.18.19.29.45.29.71 0 .26-.11.521-.29.71-.05.04-.1.09-.16.12a.559.559 0 0 1-.17.09c-.06.03-.12.05-.19.06-.06.01-.13.02-.19.02-.26 0-.52-.11-.71-.29A1.05 1.05 0 0 1 1 6c0-.26.11-.52.29-.71.24-.23.58-.34.9-.269a.6.6 0 0 1 .19.058c.06.021.12.051.17.091z\" fill-rule=\"evenodd\"/>");
document.write("                </svg>");
document.write("                სარჩევი");
document.write("            </h2>");
document.write("            <span class=\"toctogglespan\"><label class=\"toctogglelabel\" for=\"toctogglecheckbox\" onclick=\"toggletoc()\"></label></span>");
document.write("        </div>");

document.write("        <ul id=\"toclists\">");
document.write("            <li>");
document.write("                <a href=\"#", toc_header_1, "\">");
document.write("                    <span class=\"tocnumber\">1.</span>");
document.write("                    <span class=\"toctext\">", toc_header_1, "</span>");
document.write("                </a>");
if (typeof toc_subheader_11 !== 'undefined') {
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_11, "\">");
document.write("                        <span class=\"tocnumber\">1.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_11, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_12 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_12, "\">");
document.write("                        <span class=\"tocnumber\">1.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_12, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_13 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_13, "\">");
document.write("                        <span class=\"tocnumber\">1.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_13, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_14 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_14, "\">");
document.write("                        <span class=\"tocnumber\">1.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_14, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_15 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_15, "\">");
document.write("                        <span class=\"tocnumber\">1.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_15, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_16 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_16, "\">");
document.write("                        <span class=\"tocnumber\">1.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_16, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_17 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_17, "\">");
document.write("                        <span class=\"tocnumber\">1.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_17, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_18 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_18, "\">");
document.write("                        <span class=\"tocnumber\">1.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_18, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_19 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_19, "\">");
document.write("                        <span class=\"tocnumber\">1.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_19, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_110 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_110, "\">");
document.write("                        <span class=\"tocnumber\">1.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_110, "</span>");
document.write("                    </a>");
document.write("                  </li>");
}
}
}
}
}
}
}
}
}
}
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_2 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_2, "\">");
document.write("                    <span class=\"tocnumber\">2.</span>");
document.write("                    <span class=\"toctext\">", toc_header_2, "</span>");
document.write("                </a>");
if (typeof toc_subheader_21 !== 'undefined') {
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_21, "\">");
document.write("                        <span class=\"tocnumber\">2.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_21, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_22 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_22, "\">");
document.write("                        <span class=\"tocnumber\">2.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_22, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_23 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_23, "\">");
document.write("                        <span class=\"tocnumber\">2.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_23, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_24 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_24, "\">");
document.write("                        <span class=\"tocnumber\">2.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_24, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_25 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_25, "\">");
document.write("                        <span class=\"tocnumber\">2.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_25, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_26 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_26, "\">");
document.write("                        <span class=\"tocnumber\">2.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_26, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_27 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_27, "\">");
document.write("                        <span class=\"tocnumber\">2.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_27, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_28 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_28, "\">");
document.write("                        <span class=\"tocnumber\">2.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_28, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_29 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_29, "\">");
document.write("                        <span class=\"tocnumber\">2.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_29, "</span>");
document.write("                    </a>");
document.write("                  </li>");

if (typeof toc_subheader_210 !== 'undefined') {
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_210, "\">");
document.write("                        <span class=\"tocnumber\">2.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_210, "</span>");
document.write("                    </a>");
document.write("                  </li>");
}
}
}
}
}
}
}
}
}
}
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_3 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_3, "\">");
document.write("                    <span class=\"tocnumber\">3.</span>");
document.write("                    <span class=\"toctext\">", toc_header_3, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_31, "\">");
document.write("                        <span class=\"tocnumber\">3.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_31, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_32, "\">");
document.write("                        <span class=\"tocnumber\">3.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_32, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_33, "\">");
document.write("                        <span class=\"tocnumber\">3.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_33, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_34, "\">");
document.write("                        <span class=\"tocnumber\">3.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_34, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_35, "\">");
document.write("                        <span class=\"tocnumber\">3.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_35, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_36, "\">");
document.write("                        <span class=\"tocnumber\">3.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_36, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_37, "\">");
document.write("                        <span class=\"tocnumber\">3.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_37, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_38, "\">");
document.write("                        <span class=\"tocnumber\">3.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_38, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_39, "\">");
document.write("                        <span class=\"tocnumber\">3.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_39, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_310, "\">");
document.write("                        <span class=\"tocnumber\">3.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_310, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_4 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_4, "\">");
document.write("                    <span class=\"tocnumber\">4.</span>");
document.write("                    <span class=\"toctext\">", toc_header_4, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_41, "\">");
document.write("                        <span class=\"tocnumber\">4.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_41, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_42, "\">");
document.write("                        <span class=\"tocnumber\">4.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_42, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_43, "\">");
document.write("                        <span class=\"tocnumber\">4.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_43, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_44, "\">");
document.write("                        <span class=\"tocnumber\">4.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_44, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_45, "\">");
document.write("                        <span class=\"tocnumber\">4.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_45, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_46, "\">");
document.write("                        <span class=\"tocnumber\">4.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_46, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_47, "\">");
document.write("                        <span class=\"tocnumber\">4.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_47, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_48, "\">");
document.write("                        <span class=\"tocnumber\">4.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_48, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_49, "\">");
document.write("                        <span class=\"tocnumber\">4.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_49, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_410, "\">");
document.write("                        <span class=\"tocnumber\">4.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_410, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_5 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_5, "\">");
document.write("                    <span class=\"tocnumber\">5.</span>");
document.write("                    <span class=\"toctext\">", toc_header_5, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_51, "\">");
document.write("                        <span class=\"tocnumber\">5.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_51, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_52, "\">");
document.write("                        <span class=\"tocnumber\">5.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_52, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_53, "\">");
document.write("                        <span class=\"tocnumber\">5.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_53, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_54, "\">");
document.write("                        <span class=\"tocnumber\">5.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_54, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_55, "\">");
document.write("                        <span class=\"tocnumber\">5.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_55, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_56, "\">");
document.write("                        <span class=\"tocnumber\">5.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_56, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_57, "\">");
document.write("                        <span class=\"tocnumber\">5.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_57, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_58, "\">");
document.write("                        <span class=\"tocnumber\">5.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_58, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_59, "\">");
document.write("                        <span class=\"tocnumber\">5.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_59, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_510, "\">");
document.write("                        <span class=\"tocnumber\">5.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_510, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_6 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_6, "\">");
document.write("                    <span class=\"tocnumber\">6.</span>");
document.write("                    <span class=\"toctext\">", toc_header_6, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_61, "\">");
document.write("                        <span class=\"tocnumber\">6.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_61, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_62, "\">");
document.write("                        <span class=\"tocnumber\">6.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_62, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_63, "\">");
document.write("                        <span class=\"tocnumber\">6.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_63, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_64, "\">");
document.write("                        <span class=\"tocnumber\">6.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_64, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_65, "\">");
document.write("                        <span class=\"tocnumber\">6.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_65, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_66, "\">");
document.write("                        <span class=\"tocnumber\">6.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_66, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_67, "\">");
document.write("                        <span class=\"tocnumber\">6.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_67, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_68, "\">");
document.write("                        <span class=\"tocnumber\">6.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_68, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_69, "\">");
document.write("                        <span class=\"tocnumber\">6.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_69, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_610, "\">");
document.write("                        <span class=\"tocnumber\">6.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_610, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_7 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_7, "\">");
document.write("                    <span class=\"tocnumber\">7.</span>");
document.write("                    <span class=\"toctext\">", toc_header_7, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_71, "\">");
document.write("                        <span class=\"tocnumber\">7.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_71, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_72, "\">");
document.write("                        <span class=\"tocnumber\">7.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_72, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_73, "\">");
document.write("                        <span class=\"tocnumber\">7.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_73, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_74, "\">");
document.write("                        <span class=\"tocnumber\">7.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_74, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_75, "\">");
document.write("                        <span class=\"tocnumber\">7.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_75, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_76, "\">");
document.write("                        <span class=\"tocnumber\">7.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_76, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_77, "\">");
document.write("                        <span class=\"tocnumber\">7.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_77, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_78, "\">");
document.write("                        <span class=\"tocnumber\">7.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_78, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_79, "\">");
document.write("                        <span class=\"tocnumber\">7.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_79, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_710, "\">");
document.write("                        <span class=\"tocnumber\">7.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_710, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_8 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_8, "\">");
document.write("                    <span class=\"tocnumber\">8.</span>");
document.write("                    <span class=\"toctext\">", toc_header_8, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_81, "\">");
document.write("                        <span class=\"tocnumber\">8.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_81, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_82, "\">");
document.write("                        <span class=\"tocnumber\">8.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_82, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_83, "\">");
document.write("                        <span class=\"tocnumber\">8.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_83, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_84, "\">");
document.write("                        <span class=\"tocnumber\">8.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_84, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_85, "\">");
document.write("                        <span class=\"tocnumber\">8.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_85, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_86, "\">");
document.write("                        <span class=\"tocnumber\">8.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_86, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_87, "\">");
document.write("                        <span class=\"tocnumber\">8.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_87, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_88, "\">");
document.write("                        <span class=\"tocnumber\">8.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_88, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_89, "\">");
document.write("                        <span class=\"tocnumber\">8.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_89, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_810, "\">");
document.write("                        <span class=\"tocnumber\">8.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_810, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_9 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_9, "\">");
document.write("                    <span class=\"tocnumber\">9.</span>");
document.write("                    <span class=\"toctext\">", toc_header_9, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_91, "\">");
document.write("                        <span class=\"tocnumber\">9.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_91, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_92, "\">");
document.write("                        <span class=\"tocnumber\">9.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_92, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_93, "\">");
document.write("                        <span class=\"tocnumber\">9.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_93, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_94, "\">");
document.write("                        <span class=\"tocnumber\">9.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_94, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_95, "\">");
document.write("                        <span class=\"tocnumber\">9.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_95, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_96, "\">");
document.write("                        <span class=\"tocnumber\">9.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_96, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_97, "\">");
document.write("                        <span class=\"tocnumber\">9.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_97, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_98, "\">");
document.write("                        <span class=\"tocnumber\">9.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_98, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_99, "\">");
document.write("                        <span class=\"tocnumber\">9.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_99, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_910, "\">");
document.write("                        <span class=\"tocnumber\">9.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_910, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
if (typeof toc_header_10 !== 'undefined') {
document.write("            <li>");
document.write("                <a href=\"#", toc_header_10, "\">");
document.write("                    <span class=\"tocnumber\">10.</span>");
document.write("                    <span class=\"toctext\">", toc_header_10, "</span>");
document.write("                </a>");
document.write("                <ul>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_101, "\">");
document.write("                        <span class=\"tocnumber\">10.1.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_101, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_102, "\">");
document.write("                        <span class=\"tocnumber\">10.2.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_102, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_103, "\">");
document.write("                        <span class=\"tocnumber\">10.3.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_103, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_104, "\">");
document.write("                        <span class=\"tocnumber\">10.4.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_104, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_105, "\">");
document.write("                        <span class=\"tocnumber\">10.5.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_105, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_106, "\">");
document.write("                        <span class=\"tocnumber\">10.6.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_106, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_107, "\">");
document.write("                        <span class=\"tocnumber\">10.7.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_107, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_108, "\">");
document.write("                        <span class=\"tocnumber\">10.8.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_108, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_109, "\">");
document.write("                        <span class=\"tocnumber\">10.9.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_109, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                  <li>");
document.write("                    <a href=\"#", toc_subheader_1010, "\">");
document.write("                        <span class=\"tocnumber\">10.10.</span>");
document.write("                        <span class=\"toctext\">", toc_subheader_1010, "</span>");
document.write("                    </a>");
document.write("                  </li>");
document.write("                </ul>");
document.write("            </li>");
document.write("        </ul>");
document.write("    </div>");
}
}
}
}
}
}
}
}
}
}

function toggletoc() {
    var togglelist = document.getElementById("toclists");

    if (togglelist.style.display === "none") {
    togglelist.style.display = "block";        
} else {
    togglelist.style.display = "none";
}
}