package away3d.primitives
{
   import away3d.arcane;
   import away3d.core.base.CompactSubGeometry;
   import away3d.core.base.Geometry;
   import away3d.core.base.ISubGeometry;
   import away3d.errors.AbstractMethodError;
   import flash.geom.Matrix3D;
   
   use namespace arcane;
   
   public class PrimitiveBase extends Geometry
   {
      
      protected var _geomDirty:Boolean = true;
      
      protected var _uvDirty:Boolean = true;
      
      private var _subGeometry:CompactSubGeometry;
      
      public function PrimitiveBase()
      {
         super();
         this._subGeometry = new CompactSubGeometry();
         this._subGeometry.autoGenerateDummyUVs = false;
         addSubGeometry(this._subGeometry);
      }
      
      override public function get subGeometries() : Vector.<ISubGeometry>
      {
         if(this._geomDirty)
         {
            this.updateGeometry();
         }
         if(this._uvDirty)
         {
            this.updateUVs();
         }
         return super.subGeometries;
      }
      
      override public function clone() : Geometry
      {
         if(this._geomDirty)
         {
            this.updateGeometry();
         }
         if(this._uvDirty)
         {
            this.updateUVs();
         }
         return super.clone();
      }
      
      override public function scale(scale:Number) : void
      {
         if(this._geomDirty)
         {
            this.updateGeometry();
         }
         super.scale(scale);
      }
      
      override public function scaleUV(scaleU:Number = 1, scaleV:Number = 1) : void
      {
         if(this._uvDirty)
         {
            this.updateUVs();
         }
         super.scaleUV(scaleU,scaleV);
      }
      
      override public function applyTransformation(transform:Matrix3D) : void
      {
         if(this._geomDirty)
         {
            this.updateGeometry();
         }
         super.applyTransformation(transform);
      }
      
      protected function buildGeometry(target:CompactSubGeometry) : void
      {
         throw new AbstractMethodError();
      }
      
      protected function buildUVs(target:CompactSubGeometry) : void
      {
         throw new AbstractMethodError();
      }
      
      protected function invalidateGeometry() : void
      {
         this._geomDirty = true;
      }
      
      protected function invalidateUVs() : void
      {
         this._uvDirty = true;
      }
      
      private function updateGeometry() : void
      {
         this.buildGeometry(this._subGeometry);
         this._geomDirty = false;
      }
      
      private function updateUVs() : void
      {
         this.buildUVs(this._subGeometry);
         this._uvDirty = false;
      }
      
      override arcane function validate() : void
      {
         if(this._geomDirty)
         {
            this.updateGeometry();
         }
         if(this._uvDirty)
         {
            this.updateUVs();
         }
      }
   }
}

