package away3d.core.base
{
   import away3d.arcane;
   import away3d.core.managers.Stage3DProxy;
   import away3d.errors.AbstractMethodError;
   import flash.display3D.Context3D;
   import flash.display3D.IndexBuffer3D;
   import flash.display3D.VertexBuffer3D;
   import flash.geom.Matrix3D;
   import flash.geom.Vector3D;
   
   use namespace arcane;
   
   public class SubGeometryBase
   {
      
      private var _parentGeometry:Geometry;
      
      protected var _vertexData:Vector.<Number>;
      
      protected var _faceNormalsDirty:Boolean = true;
      
      protected var _faceTangentsDirty:Boolean = true;
      
      protected var _faceTangents:Vector.<Number>;
      
      protected var _indices:Vector.<uint>;
      
      protected var _indexBuffer:Vector.<IndexBuffer3D> = new Vector.<IndexBuffer3D>(8);
      
      protected var _numIndices:uint;
      
      protected var _indexBufferContext:Vector.<Context3D> = new Vector.<Context3D>(8);
      
      protected var _indicesInvalid:Vector.<Boolean> = new Vector.<Boolean>(8,true);
      
      protected var _numTriangles:uint;
      
      protected var _autoDeriveVertexNormals:Boolean = true;
      
      protected var _autoDeriveVertexTangents:Boolean = true;
      
      protected var _autoGenerateUVs:Boolean = false;
      
      private var _useFaceWeights:Boolean = false;
      
      protected var _vertexNormalsDirty:Boolean = true;
      
      protected var _vertexTangentsDirty:Boolean = true;
      
      protected var _faceNormals:Vector.<Number>;
      
      protected var _faceWeights:Vector.<Number>;
      
      private var _scaleU:Number = 1;
      
      private var _scaleV:Number = 1;
      
      protected var _uvsDirty:Boolean = true;
      
      public function SubGeometryBase()
      {
         super();
      }
      
      public function get autoGenerateDummyUVs() : Boolean
      {
         return this._autoGenerateUVs;
      }
      
      public function set autoGenerateDummyUVs(value:Boolean) : void
      {
         this._autoGenerateUVs = value;
         this._uvsDirty = value;
      }
      
      public function get autoDeriveVertexNormals() : Boolean
      {
         return this._autoDeriveVertexNormals;
      }
      
      public function set autoDeriveVertexNormals(value:Boolean) : void
      {
         this._autoDeriveVertexNormals = value;
         this._vertexNormalsDirty = value;
      }
      
      public function get useFaceWeights() : Boolean
      {
         return this._useFaceWeights;
      }
      
      public function set useFaceWeights(value:Boolean) : void
      {
         this._useFaceWeights = value;
         if(this._autoDeriveVertexNormals)
         {
            this._vertexNormalsDirty = true;
         }
         if(this._autoDeriveVertexTangents)
         {
            this._vertexTangentsDirty = true;
         }
         this._faceNormalsDirty = true;
      }
      
      public function get numTriangles() : uint
      {
         return this._numTriangles;
      }
      
      public function getIndexBuffer(stage3DProxy:Stage3DProxy) : IndexBuffer3D
      {
         var contextIndex:int = stage3DProxy._stage3DIndex;
         var context:Context3D = stage3DProxy._context3D;
         if(!this._indexBuffer[contextIndex] || this._indexBufferContext[contextIndex] != context)
         {
            this._indexBuffer[contextIndex] = context.createIndexBuffer(this._numIndices);
            this._indexBufferContext[contextIndex] = context;
            this._indicesInvalid[contextIndex] = true;
         }
         if(this._indicesInvalid[contextIndex])
         {
            this._indexBuffer[contextIndex].uploadFromVector(this._indices,0,this._numIndices);
            this._indicesInvalid[contextIndex] = false;
         }
         return this._indexBuffer[contextIndex];
      }
      
      protected function updateFaceTangents() : void
      {
         var i:uint = 0;
         var index1:uint = 0;
         var index2:uint = 0;
         var index3:uint = 0;
         var ui:uint = 0;
         var vi:uint = 0;
         var v0:Number = NaN;
         var dv1:Number = NaN;
         var dv2:Number = NaN;
         var denom:Number = NaN;
         var x0:Number = NaN;
         var y0:Number = NaN;
         var z0:Number = NaN;
         var dx1:Number = NaN;
         var dy1:Number = NaN;
         var dz1:Number = NaN;
         var dx2:Number = NaN;
         var dy2:Number = NaN;
         var dz2:Number = NaN;
         var cx:Number = NaN;
         var cy:Number = NaN;
         var cz:Number = NaN;
         var len:uint = this._indices.length;
         var vertices:Vector.<Number> = this._vertexData;
         var uvs:Vector.<Number> = this.UVData;
         var posStride:int = int(this.vertexStride);
         var posOffset:int = this.vertexOffset;
         var texStride:int = int(this.UVStride);
         var texOffset:int = this.UVOffset;
         this._faceTangents = this._faceTangents || new Vector.<Number>(this._indices.length,true);
         while(i < len)
         {
            index1 = this._indices[i];
            index2 = this._indices[i + 1];
            index3 = this._indices[i + 2];
            ui = texOffset + index1 * texStride + 1;
            v0 = uvs[ui];
            ui = texOffset + index2 * texStride + 1;
            dv1 = uvs[ui] - v0;
            ui = texOffset + index3 * texStride + 1;
            dv2 = uvs[ui] - v0;
            vi = posOffset + index1 * posStride;
            x0 = vertices[vi];
            y0 = vertices[uint(vi + 1)];
            z0 = vertices[uint(vi + 2)];
            vi = posOffset + index2 * posStride;
            dx1 = vertices[uint(vi)] - x0;
            dy1 = vertices[uint(vi + 1)] - y0;
            dz1 = vertices[uint(vi + 2)] - z0;
            vi = posOffset + index3 * posStride;
            dx2 = vertices[uint(vi)] - x0;
            dy2 = vertices[uint(vi + 1)] - y0;
            dz2 = vertices[uint(vi + 2)] - z0;
            cx = dv2 * dx1 - dv1 * dx2;
            cy = dv2 * dy1 - dv1 * dy2;
            cz = dv2 * dz1 - dv1 * dz2;
            denom = 1 / Math.sqrt(cx * cx + cy * cy + cz * cz);
            this._faceTangents[i++] = denom * cx;
            this._faceTangents[i++] = denom * cy;
            this._faceTangents[i++] = denom * cz;
         }
         this._faceTangentsDirty = false;
      }
      
      private function updateFaceNormals() : void
      {
         var i:uint = 0;
         var j:uint = 0;
         var k:uint = 0;
         var index:uint = 0;
         var x1:Number = NaN;
         var x2:Number = NaN;
         var x3:Number = NaN;
         var y1:Number = NaN;
         var y2:Number = NaN;
         var y3:Number = NaN;
         var z1:Number = NaN;
         var z2:Number = NaN;
         var z3:Number = NaN;
         var dx1:Number = NaN;
         var dy1:Number = NaN;
         var dz1:Number = NaN;
         var dx2:Number = NaN;
         var dy2:Number = NaN;
         var dz2:Number = NaN;
         var cx:Number = NaN;
         var cy:Number = NaN;
         var cz:Number = NaN;
         var d:Number = NaN;
         var w:Number = NaN;
         var len:uint = this._indices.length;
         var vertices:Vector.<Number> = this._vertexData;
         var posStride:int = int(this.vertexStride);
         var posOffset:int = this.vertexOffset;
         this._faceNormals = this._faceNormals || new Vector.<Number>(len,true);
         if(this._useFaceWeights)
         {
            this._faceWeights = this._faceWeights || new Vector.<Number>(len / 3,true);
         }
         while(i < len)
         {
            index = posOffset + this._indices[i++] * posStride;
            x1 = vertices[index];
            y1 = vertices[index + 1];
            z1 = vertices[index + 2];
            index = posOffset + this._indices[i++] * posStride;
            x2 = vertices[index];
            y2 = vertices[index + 1];
            z2 = vertices[index + 2];
            index = posOffset + this._indices[i++] * posStride;
            x3 = vertices[index];
            y3 = vertices[index + 1];
            z3 = vertices[index + 2];
            dx1 = x3 - x1;
            dy1 = y3 - y1;
            dz1 = z3 - z1;
            dx2 = x2 - x1;
            dy2 = y2 - y1;
            dz2 = z2 - z1;
            cx = dz1 * dy2 - dy1 * dz2;
            cy = dx1 * dz2 - dz1 * dx2;
            cz = dy1 * dx2 - dx1 * dy2;
            d = Math.sqrt(cx * cx + cy * cy + cz * cz);
            if(this._useFaceWeights)
            {
               w = d * 10000;
               if(w < 1)
               {
                  w = 1;
               }
               this._faceWeights[k++] = w;
            }
            d = 1 / d;
            this._faceNormals[j++] = cx * d;
            this._faceNormals[j++] = cy * d;
            this._faceNormals[j++] = cz * d;
         }
         this._faceNormalsDirty = false;
      }
      
      protected function updateVertexNormals(target:Vector.<Number>) : Vector.<Number>
      {
         var v1:uint = 0;
         var i:uint = 0;
         var k:uint = 0;
         var index:uint = 0;
         var weight:Number = NaN;
         var vx:Number = NaN;
         var vy:Number = NaN;
         var vz:Number = NaN;
         var d:Number = NaN;
         if(this._faceNormalsDirty)
         {
            this.updateFaceNormals();
         }
         var f1:uint = 0;
         var f2:uint = 1;
         var f3:uint = 2;
         var lenV:uint = this._vertexData.length;
         var normalStride:int = int(this.vertexNormalStride);
         var normalOffset:int = this.vertexNormalOffset;
         target ||= new Vector.<Number>(lenV,true);
         v1 = uint(normalOffset);
         while(v1 < lenV)
         {
            target[v1] = 0;
            target[v1 + 1] = 0;
            target[v1 + 2] = 0;
            v1 += normalStride;
         }
         var lenI:uint = this._indices.length;
         while(i < lenI)
         {
            weight = this._useFaceWeights ? this._faceWeights[k++] : 1;
            index = normalOffset + this._indices[i++] * normalStride;
            var _temp_5:* = target;
            var _loc18_:uint = index++;
            _temp_5[_loc18_] += this._faceNormals[f1] * weight;
            var _temp_7:* = target;
            var _loc19_:uint = index++;
            _temp_7[_loc19_] += this._faceNormals[f2] * weight;
            target[index] += this._faceNormals[f3] * weight;
            index = normalOffset + this._indices[i++] * normalStride;
            var _temp_10:* = target;
            var _loc20_:uint = index++;
            _temp_10[_loc20_] += this._faceNormals[f1] * weight;
            var _temp_12:* = target;
            var _loc21_:uint = index++;
            _temp_12[_loc21_] += this._faceNormals[f2] * weight;
            target[index] += this._faceNormals[f3] * weight;
            index = normalOffset + this._indices[i++] * normalStride;
            var _temp_15:* = target;
            var _loc22_:uint = index++;
            _temp_15[_loc22_] += this._faceNormals[f1] * weight;
            var _temp_17:* = target;
            var _loc23_:uint = index++;
            _temp_17[_loc23_] += this._faceNormals[f2] * weight;
            target[index] += this._faceNormals[f3] * weight;
            f1 += 3;
            f2 += 3;
            f3 += 3;
         }
         v1 = uint(normalOffset);
         while(v1 < lenV)
         {
            vx = target[v1];
            vy = target[v1 + 1];
            vz = target[v1 + 2];
            d = 1 / Math.sqrt(vx * vx + vy * vy + vz * vz);
            target[v1] = vx * d;
            target[v1 + 1] = vy * d;
            target[v1 + 2] = vz * d;
            v1 += normalStride;
         }
         this._vertexNormalsDirty = false;
         return target;
      }
      
      protected function updateVertexTangents(target:Vector.<Number>) : Vector.<Number>
      {
         var i:uint = 0;
         var k:uint = 0;
         var index:uint = 0;
         var weight:Number = NaN;
         var vx:Number = NaN;
         var vy:Number = NaN;
         var vz:Number = NaN;
         var d:Number = NaN;
         if(this._faceTangentsDirty)
         {
            this.updateFaceTangents();
         }
         var lenV:uint = this._vertexData.length;
         var tangentStride:int = int(this.vertexTangentStride);
         var tangentOffset:int = this.vertexTangentOffset;
         target ||= new Vector.<Number>(lenV,true);
         i = uint(tangentOffset);
         while(i < lenV)
         {
            target[i] = 0;
            target[i + 1] = 0;
            target[i + 2] = 0;
            i += tangentStride;
         }
         var lenI:uint = this._indices.length;
         var f1:uint = 0;
         var f2:uint = 1;
         var f3:uint = 2;
         i = 0;
         while(i < lenI)
         {
            weight = this._useFaceWeights ? this._faceWeights[k++] : 1;
            index = tangentOffset + this._indices[i++] * tangentStride;
            var _temp_5:* = target;
            var _loc17_:uint = index++;
            _temp_5[_loc17_] += this._faceTangents[f1] * weight;
            var _temp_7:* = target;
            var _loc18_:uint = index++;
            _temp_7[_loc18_] += this._faceTangents[f2] * weight;
            target[index] += this._faceTangents[f3] * weight;
            index = tangentOffset + this._indices[i++] * tangentStride;
            var _temp_10:* = target;
            var _loc19_:uint = index++;
            _temp_10[_loc19_] += this._faceTangents[f1] * weight;
            var _temp_12:* = target;
            var _loc20_:uint = index++;
            _temp_12[_loc20_] += this._faceTangents[f2] * weight;
            target[index] += this._faceTangents[f3] * weight;
            index = tangentOffset + this._indices[i++] * tangentStride;
            var _temp_15:* = target;
            var _loc21_:uint = index++;
            _temp_15[_loc21_] += this._faceTangents[f1] * weight;
            var _temp_17:* = target;
            var _loc22_:uint = index++;
            _temp_17[_loc22_] += this._faceTangents[f2] * weight;
            target[index] += this._faceTangents[f3] * weight;
            f1 += 3;
            f2 += 3;
            f3 += 3;
         }
         i = uint(tangentOffset);
         while(i < lenV)
         {
            vx = target[i];
            vy = target[i + 1];
            vz = target[i + 2];
            d = 1 / Math.sqrt(vx * vx + vy * vy + vz * vz);
            target[i] = vx * d;
            target[i + 1] = vy * d;
            target[i + 2] = vz * d;
            i += tangentStride;
         }
         this._vertexTangentsDirty = false;
         return target;
      }
      
      public function dispose() : void
      {
         this.disposeIndexBuffers(this._indexBuffer);
         this._indices = null;
         this._indexBufferContext = null;
         this._faceNormals = null;
         this._faceWeights = null;
         this._faceTangents = null;
         this._vertexData = null;
      }
      
      public function get indexData() : Vector.<uint>
      {
         return this._indices;
      }
      
      public function updateIndexData(indices:Vector.<uint>) : void
      {
         this._indices = indices;
         this._numIndices = indices.length;
         var numTriangles:int = this._numIndices / 3;
         if(this._numTriangles != numTriangles)
         {
            this.disposeIndexBuffers(this._indexBuffer);
         }
         this._numTriangles = numTriangles;
         this.invalidateBuffers(this._indicesInvalid);
         this._faceNormalsDirty = true;
         if(this._autoDeriveVertexNormals)
         {
            this._vertexNormalsDirty = true;
         }
         if(this._autoDeriveVertexTangents)
         {
            this._vertexTangentsDirty = true;
         }
      }
      
      protected function disposeIndexBuffers(buffers:Vector.<IndexBuffer3D>) : void
      {
         for(var i:int = 0; i < 8; i++)
         {
            if(Boolean(buffers[i]))
            {
               buffers[i].dispose();
               buffers[i] = null;
            }
         }
      }
      
      protected function disposeVertexBuffers(buffers:Vector.<VertexBuffer3D>) : void
      {
         for(var i:int = 0; i < 8; i++)
         {
            if(Boolean(buffers[i]))
            {
               buffers[i].dispose();
               buffers[i] = null;
            }
         }
      }
      
      public function get autoDeriveVertexTangents() : Boolean
      {
         return this._autoDeriveVertexTangents;
      }
      
      public function set autoDeriveVertexTangents(value:Boolean) : void
      {
         this._autoDeriveVertexTangents = value;
         this._vertexTangentsDirty = value;
      }
      
      public function get faceNormals() : Vector.<Number>
      {
         if(this._faceNormalsDirty)
         {
            this.updateFaceNormals();
         }
         return this._faceNormals;
      }
      
      protected function invalidateBuffers(invalid:Vector.<Boolean>) : void
      {
         for(var i:int = 0; i < 8; i++)
         {
            invalid[i] = true;
         }
      }
      
      public function get UVStride() : uint
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexData() : Vector.<Number>
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexPositionData() : Vector.<Number>
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexNormalData() : Vector.<Number>
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexTangentData() : Vector.<Number>
      {
         throw new AbstractMethodError();
      }
      
      public function get UVData() : Vector.<Number>
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexStride() : uint
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexNormalStride() : uint
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexTangentStride() : uint
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexOffset() : int
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexNormalOffset() : int
      {
         throw new AbstractMethodError();
      }
      
      public function get vertexTangentOffset() : int
      {
         throw new AbstractMethodError();
      }
      
      public function get UVOffset() : int
      {
         throw new AbstractMethodError();
      }
      
      protected function invalidateBounds() : void
      {
         if(Boolean(this._parentGeometry))
         {
            this._parentGeometry.invalidateBounds(ISubGeometry(this));
         }
      }
      
      public function get parentGeometry() : Geometry
      {
         return this._parentGeometry;
      }
      
      public function set parentGeometry(value:Geometry) : void
      {
         this._parentGeometry = value;
      }
      
      public function get scaleU() : Number
      {
         return this._scaleU;
      }
      
      public function get scaleV() : Number
      {
         return this._scaleV;
      }
      
      public function scaleUV(scaleU:Number = 1, scaleV:Number = 1) : void
      {
         var offset:int = this.UVOffset;
         var stride:int = int(this.UVStride);
         var uvs:Vector.<Number> = this.UVData;
         var len:int = int(uvs.length);
         var ratioU:Number = scaleU / this._scaleU;
         var ratioV:Number = scaleV / this._scaleV;
         for(var i:uint = uint(offset); i < len; i += stride)
         {
            uvs[i] *= ratioU;
            uvs[i + 1] *= ratioV;
         }
         this._scaleU = scaleU;
         this._scaleV = scaleV;
      }
      
      public function scale(scale:Number) : void
      {
         var vertices:Vector.<Number> = this.UVData;
         var len:uint = vertices.length;
         var offset:int = this.vertexOffset;
         var stride:int = int(this.vertexStride);
         for(var i:uint = uint(offset); i < len; i += stride)
         {
            vertices[i] *= scale;
            vertices[i + 1] *= scale;
            vertices[i + 2] *= scale;
         }
      }
      
      public function applyTransformation(transform:Matrix3D) : void
      {
         var i:uint = 0;
         var i1:uint = 0;
         var i2:uint = 0;
         var invTranspose:Matrix3D = null;
         var vertices:Vector.<Number> = this._vertexData;
         var normals:Vector.<Number> = this.vertexNormalData;
         var tangents:Vector.<Number> = this.vertexTangentData;
         var posStride:int = int(this.vertexStride);
         var normalStride:int = int(this.vertexNormalStride);
         var tangentStride:int = int(this.vertexTangentStride);
         var posOffset:int = this.vertexOffset;
         var normalOffset:int = this.vertexNormalOffset;
         var tangentOffset:int = this.vertexTangentOffset;
         var len:uint = vertices.length / posStride;
         var vector:Vector3D = new Vector3D();
         var bakeNormals:Boolean = normals != null;
         var bakeTangents:Boolean = tangents != null;
         if(bakeNormals || bakeTangents)
         {
            invTranspose = transform.clone();
            invTranspose.invert();
            invTranspose.transpose();
         }
         var vi0:int = posOffset;
         var ni0:int = normalOffset;
         var ti0:int = tangentOffset;
         for(i = 0; i < len; i++)
         {
            i1 = vi0 + 1;
            i2 = vi0 + 2;
            vector.x = vertices[vi0];
            vector.y = vertices[i1];
            vector.z = vertices[i2];
            vector = transform.transformVector(vector);
            vertices[vi0] = vector.x;
            vertices[i1] = vector.y;
            vertices[i2] = vector.z;
            vi0 += posStride;
            if(bakeNormals)
            {
               i1 = ni0 + 1;
               i2 = ni0 + 2;
               vector.x = normals[ni0];
               vector.y = normals[i1];
               vector.z = normals[i2];
               vector = invTranspose.deltaTransformVector(vector);
               vector.normalize();
               normals[ni0] = vector.x;
               normals[i1] = vector.y;
               normals[i2] = vector.z;
               ni0 += normalStride;
            }
            if(bakeTangents)
            {
               i1 = ti0 + 1;
               i2 = ti0 + 2;
               vector.x = tangents[ti0];
               vector.y = tangents[i1];
               vector.z = tangents[i2];
               vector = invTranspose.deltaTransformVector(vector);
               vector.normalize();
               tangents[ti0] = vector.x;
               tangents[i1] = vector.y;
               tangents[i2] = vector.z;
               ti0 += tangentStride;
            }
         }
      }
      
      protected function updateDummyUVs(target:Vector.<Number>) : Vector.<Number>
      {
         var idx:uint = 0;
         var uvIdx:uint = 0;
         this._uvsDirty = false;
         var stride:int = int(this.UVStride);
         var skip:int = stride - 2;
         var len:uint = this._vertexData.length / this.vertexStride * stride;
         if(!target)
         {
            target = new Vector.<Number>();
         }
         target.fixed = false;
         target.length = len;
         target.fixed = true;
         idx = uint(this.UVOffset);
         uvIdx = 0;
         while(idx < len)
         {
            target[idx++] = uvIdx * 0.5;
            target[idx++] = 1 - (uvIdx & 1);
            idx += skip;
            if(++uvIdx == 3)
            {
               uvIdx = 0;
            }
         }
         return target;
      }
   }
}

